import { createContext, useCallback, useContext, useEffect, useMemo, useState, type ReactNode } from "react";
import type { AttendanceDataset } from "../../shared/types/attendance";
export interface TeachingClass { id:string; subject:string; class_code:string; section:string; grade_level:string; term:string; source_filename:string|null; uploaded_at:string|null; student_count:number; session_count:number; assigned:boolean }
export interface TeacherAccount { id:string; display_name:string; email:string }
export interface PendingTeacherRequest { id:string; display_name:string; email:string; created_at:string }
export interface AppUser { id:string; school_id:string; display_name:string; email:string; school_name:string; roles:string[]; school_roles:string[] }
export interface ReportRequest { classId:string; reportType:"class_analytics"; format:"csv"|"xlsx"; filters:{section:string;dateRange:string;startDate:string;endDate:string;studentSearchApplied:boolean;studentCount:number;sessionCount:number} }
export interface ReportReceipt { id:string; generatedAt:string }
const emptyDataset=():AttendanceDataset=>({metadata:{subjectTitle:"",subjectCode:"",term:"",program:"",section:"",scheduleDays:[],scheduleTimes:[]},sections:[],dates:[],students:[],sourceName:"PostgreSQL",importedAt:""});
interface Ctx { refreshTeachers:()=>Promise<void>; approveTeacherRequest:(id:string)=>Promise<void>; pendingTeacherRequests:PendingTeacherRequest[]; user:AppUser|null; authenticated:boolean; authReady:boolean; signIn:(email:string,password:string)=>Promise<void>; signUp:(data:{name:string;school:string;email:string;password:string})=>Promise<{pendingApproval:boolean}>; signOut:()=>Promise<void>; dataset:AttendanceDataset; classes:TeachingClass[]; managementClasses:TeachingClass[]; deleteClass:(id:string)=>Promise<void>; teachers:TeacherAccount[]; activeClassId:string; activeTeacherId:string; selectClass:(id:string)=>Promise<void>; selectTeacher:(id:string)=>Promise<void>; createTeacher:(name:string,email:string,password:string,role:string)=>Promise<void>; assignClass:(classId:string,assigned:boolean)=>Promise<void>; isLoading:boolean; dataError:string; replaceDataset:(data:AttendanceDataset)=>Promise<void>; refreshClasses:()=>Promise<TeachingClass[]>; recordReport:(report:ReportRequest)=>Promise<ReportReceipt> }
const Context=createContext<Ctx|null>(null);
async function api(path:string,init?:RequestInit){try{const timeout=path==="/api/import"?90_000:30_000;const r=await fetch(path,{...init,signal:init?.signal??AbortSignal.timeout(timeout),credentials:"same-origin",cache:"no-store",headers:{...(init?.body?{"content-type":"application/json"}:{}),...init?.headers}});const type=r.headers.get("content-type")||"";if(!type.includes("application/json")){const responseText=(await r.text()).slice(0,240).replace(/<[^>]*>/g," ").replace(/\s+/g," ").trim();if(r.status===405)throw new Error("The deployed API route rejected this request. Redeploy with the Vercel API routing fix.");throw new Error(responseText?`API request failed (${r.status}). ${responseText}`:r.ok?"The server returned a page instead of API data. Check the Vercel API route configuration.":`The API returned a non-JSON response (${r.status}).`);}const b=await r.json();if(!r.ok)throw new Error([b.error||"The request failed.",b.reference?`Reference: ${b.reference}`:""].filter(Boolean).join(" "));return b;}catch(error){if(error instanceof DOMException&&error.name==="TimeoutError")throw new Error(path==="/api/import"?"Saving took longer than 90 seconds. No partial import was committed; try again or check the database connection.":"TalaTrack could not reach the database within 30 seconds. Try again.");throw error;}}
export function AttendanceDataProvider({children}:{children:ReactNode}){
 const [user,setUser]=useState<AppUser|null>(null),[authReady,setAuthReady]=useState(false);const [dataset,setDataset]=useState(emptyDataset),[classes,setClasses]=useState<TeachingClass[]>([]),[teachers,setTeachers]=useState<TeacherAccount[]>([]),[pendingTeacherRequests,setPendingTeacherRequests]=useState<PendingTeacherRequest[]>([]),[activeClassId,setActiveClassId]=useState(""),[activeTeacherId,setActiveTeacherId]=useState(""),[isLoading,setLoading]=useState(true),[dataError,setDataError]=useState("");
 const [managementClasses,setManagementClasses]=useState<TeachingClass[]>([]);
 const getClasses=useCallback(async(_target=user?.id||"")=>{const b=await api(`/api/classes`);setClasses(b.classes||[]);return b.classes||[];},[activeTeacherId,user?.id]);
 const loadClass=useCallback(async(classId:string)=>{if(!classId){setDataset(emptyDataset());setActiveClassId("");return;}setDataError("");setLoading(true);try{const b=await api(`/api/dataset?classId=${encodeURIComponent(classId)}`);if(!b.dataset)throw new Error("This class has no saved attendance yet.");setDataset(b.dataset);setActiveClassId(classId);localStorage.setItem("attendwise.activeClassId",classId);}catch(e){setDataError(e instanceof Error?e.message:"Could not load class.");}finally{setLoading(false);}},[]);
 const selectClass=useCallback(async(id:string)=>{if(id!==activeClassId)await loadClass(id);},[activeClassId,loadClass]);
 const selectTeacher=useCallback(async(id:string)=>{setActiveTeacherId(id);setDataError("");try{const b=await api(`/api/classes?teacherId=${encodeURIComponent(id)}&manage=1`);setManagementClasses(b.classes||[]);}catch(e){setManagementClasses([]);setDataError(e instanceof Error?e.message:"Could not load assignments.");}},[]);
 const refreshClasses=useCallback(()=>getClasses(),[getClasses]);
 const refreshTeachers=useCallback(async()=>{if(!(user?.school_roles.includes("administrator")||user?.school_roles.includes("technical_administrator")))return;try{const [staff,requests]=await Promise.all([api("/api/teachers"),api("/api/teacher-requests")]);setTeachers(staff.teachers||[]);setPendingTeacherRequests(requests.requests||[]);}catch(e){setTeachers([]);setPendingTeacherRequests([]);setDataError(e instanceof Error?e.message:"Could not load staff.");}},[user]);
 const signIn=useCallback(async(email:string,password:string)=>{await api("/api/auth/login",{method:"POST",body:JSON.stringify({email,password})});const b=await api("/api/auth/me");setUser(b.user);setActiveTeacherId(b.user.id);},[]);
 const signUp=useCallback(async(data:{name:string;school:string;email:string;password:string})=>{const b=await api("/api/auth/register",{method:"POST",body:JSON.stringify(data)});if(b.pendingApproval)return {pendingApproval:true};setUser(b.user);setActiveTeacherId(b.user.id);return {pendingApproval:false};},[]);
 const signOut=useCallback(async()=>{try{await api("/api/auth/logout",{method:"POST",body:"{}"});}finally{setUser(null);setTeachers([]);setPendingTeacherRequests([]);setClasses([]);setDataset(emptyDataset());setActiveClassId("");setActiveTeacherId("");}},[]);
 const createTeacher=useCallback(async(displayName:string,email:string,password:string,role:string)=>{const b=await api("/api/teachers",{method:"POST",body:JSON.stringify({displayName,email,password,role})});await refreshTeachers();await selectTeacher(b.teacher.id);},[refreshTeachers,selectTeacher]);
 const approveTeacherRequest=useCallback(async(id:string)=>{await api("/api/teacher-requests",{method:"POST",body:JSON.stringify({teacherId:id})});await refreshTeachers();},[refreshTeachers]);
 const assignClass=useCallback(async(classId:string,assigned:boolean)=>{await api("/api/class-assignments",{method:"POST",body:JSON.stringify({classId,teacherId:activeTeacherId,assigned})});await selectTeacher(activeTeacherId);await getClasses();},[activeTeacherId,selectTeacher,getClasses]);
 const deleteClass=useCallback(async(id:string)=>{await api(`/api/classes?classId=${encodeURIComponent(id)}`,{method:"DELETE"});await getClasses();if(activeTeacherId)await selectTeacher(activeTeacherId);if(activeClassId===id)await loadClass("");},[getClasses,selectTeacher,activeTeacherId,activeClassId,loadClass]);
 useEffect(()=>{let live=true;(async()=>{try{const b=await api("/api/auth/me");if(!live)return;setUser(b.user);setActiveTeacherId(b.user.id);}catch{if(live)setUser(null);}finally{if(live)setAuthReady(true);}})();return()=>{live=false;}},[]);
 useEffect(()=>{if(!authReady||!user)return;let live=true;(async()=>{setLoading(true);try{await refreshTeachers();const xs=await getClasses(activeTeacherId||user.id);if(!live)return;const saved=localStorage.getItem("attendwise.activeClassId");const chosen=xs.find((x:TeachingClass)=>x.id===saved&&x.assigned)||xs.find((x:TeachingClass)=>x.assigned);if(chosen){const b=await api(`/api/dataset?classId=${encodeURIComponent(chosen.id)}`);if(live){setDataset(b.dataset||emptyDataset());setActiveClassId(chosen.id);}}else{setDataset(emptyDataset());setActiveClassId("");}}catch(e){if(live)setDataError(e instanceof Error?e.message:"Cannot connect to PostgreSQL.");}finally{if(live)setLoading(false);}})();return()=>{live=false;}},[authReady,user?.id]);
 const replaceDataset=useCallback(async(next:AttendanceDataset)=>{const b=await api("/api/import",{method:"POST",body:JSON.stringify(next)});const xs=await getClasses(activeTeacherId);const chosen=xs.find((x:TeachingClass)=>x.id===b.classIds?.[0]&&x.assigned)||xs.find((x:TeachingClass)=>x.assigned);if(chosen)await loadClass(chosen.id);},[getClasses,activeTeacherId,loadClass]);
 const recordReport=useCallback(async(report:ReportRequest)=>{const b=await api("/api/reports",{method:"POST",body:JSON.stringify(report)});return b.report as ReportReceipt;},[]);
 const value=useMemo<Ctx>(()=>({refreshTeachers,approveTeacherRequest,pendingTeacherRequests,user,authenticated:!!user,authReady,signIn,signUp,signOut,dataset,classes,managementClasses,deleteClass,teachers,activeClassId,activeTeacherId,selectClass,selectTeacher,createTeacher,assignClass,isLoading,dataError,replaceDataset,refreshClasses,recordReport}),[managementClasses,deleteClass,refreshTeachers,approveTeacherRequest,pendingTeacherRequests,user,authReady,signIn,signUp,signOut,dataset,classes,teachers,activeClassId,activeTeacherId,selectClass,selectTeacher,createTeacher,assignClass,isLoading,dataError,replaceDataset,refreshClasses,recordReport]);
 return <Context.Provider value={value}>{children}</Context.Provider>;
}
export function useAttendanceData(){const value=useContext(Context);if(!value)throw new Error("useAttendanceData must be used inside AttendanceDataProvider");return value;}
