import { ArrowUpRight, CalendarDays, ChevronDown, ChevronRight, Filter, ShieldAlert, Upload, Users } from 'lucide-react';
import { AttendanceTrendChart } from '../../../components/charts/AttendanceTrendChart';
import { Avatar } from '../../../components/ui/Avatar';
import { Badge, RiskBadge } from '../../../components/ui/Badge';
import { Button } from '../../../components/ui/Button';
import { Card, SectionHeader } from '../../../components/ui/Card';
import { useAttendanceAnalytics } from '../../analytics/hooks/useAttendanceAnalytics';
import { useStudents } from '../../students/hooks/useStudents';
function Metric({ label, value, change, icon: Icon, tone = 'green' }: { label: string; value: string; change: string; icon: typeof Users; tone?: string }) { return <article className="metric-card"><div className="metric-top"><span className="metric-label">{label}</span><span className={`metric-icon ${tone}`}><Icon size={17} /></span></div><div className="metric-value">{value}</div><div className="metric-foot"><span className="trend positive"><ArrowUpRight size={13} />{change}</span><span>vs last period</span></div></article>; }
export function DashboardPage() { const analytics = useAttendanceAnalytics(); const studentQuery = useStudents(); const students = studentQuery.data ?? []; const data = analytics.data; return <main className="content"><div className="page-heading"><div><p className="eyebrow">Tuesday, September 30, 2024</p><h1>Good morning, Camille</h1><p className="heading-copy">Here is what is happening across your attendance workspace.</p></div><div className="heading-actions"><Button variant="secondary"><CalendarDays size={16} /> Sep 01 – Sep 30 <ChevronDown size={15} /></Button><Button><Upload size={16} /> Upload attendance</Button></div></div><div className="filter-strip"><span className="filter-context"><span className="live-dot" /> Live overview</span><button className="filter-control">All departments <ChevronDown size={14} /></button><button className="filter-control">All programs <ChevronDown size={14} /></button><button className="filter-control filter-more"><Filter size={14} /> More filters</button></div><div className="metric-grid"><Metric label="Overall attendance" value="92.4%" change="3.2%" icon={CalendarDays} /><Metric label="Students tracked" value="1,248" change="8.6%" icon={Users} tone="blue" /><Metric label="Present today" value="1,089" change="2.1%" icon={ArrowUpRight} /><Metric label="Students at risk" value="47" change="5 new" icon={ShieldAlert} tone="red" /></div><div className="dashboard-grid"><Card><SectionHeader title="Attendance trend" subtitle="Average attendance rate over the selected period." action={<Button variant="ghost">View analytics <ChevronRight size={15} /></Button>} /><AttendanceTrendChart data={data?.trendData ?? []} /></Card><Card><SectionHeader title="Today’s distribution" subtitle="Attendance status across all classes." /><div className="distribution-list dashboard-distribution">{(data?.distribution ?? []).map((item) => <div className="distribution-row" key={item.name}><span><i style={{ background: item.color }} />{item.name}</span><strong>{item.value}%</strong></div>)}</div><div className="distribution-total"><strong>92%</strong><span>present today</span></div></Card></div><Card><SectionHeader title="Students needing attention" subtitle="Students with attendance below your monitoring threshold." action={<Button variant="secondary">View at-risk students <ChevronRight size={14} /></Button>} /><div className="table-scroll"><table><thead><tr><th>Student</th><th>Section</th><th>Attendance</th><th>Absences</th><th>Risk level</th><th>Last attendance</th></tr></thead><tbody>{students.map((student) => <tr key={student.id}><td><div className="student-cell"><Avatar initials={student.initials} /><div><strong>{student.name}</strong><span>{student.program}</span></div></div></td><td>{student.section}</td><td>{student.attendanceRate}%</td><td>{student.absences}</td><td><RiskBadge level={student.riskLevel} /></td><td>{student.lastAttendance}</td></tr>)}</tbody></table></div></Card></main>; }
