import { Bell, ChevronDown, ChevronRight, CircleHelp, FileText, Filter, LayoutDashboard, Menu, Search, Settings, ShieldAlert, SlidersHorizontal, Upload, Users, X, CalendarDays } from 'lucide-react';
import type { ReactNode } from 'react';
import { Link, useLocation } from 'react-router-dom';
import { useUiStore } from '../../stores/uiStore';
import type { UserRole } from '../../types/domain';
import { Avatar } from '../ui/Avatar';

const groups = [{ label: 'Workspace', items: [{ label: 'Dashboard', path: '/app/dashboard', icon: LayoutDashboard }, { label: 'Attendance', path: '/app/attendance/records', icon: CalendarDays }, { label: 'Students', path: '/app/students', icon: Users }, { label: 'My Classes', path: '/app/classes', icon: FileText }] }, { label: 'Insights', items: [{ label: 'Analytics', path: '/app/analytics/overview', icon: SlidersHorizontal }, { label: 'At-Risk Students', path: '/app/at-risk', icon: ShieldAlert }, { label: 'Interventions', path: '/app/interventions', icon: ShieldAlert }] }, { label: 'Operations', items: [{ label: 'Reports', path: '/app/reports', icon: FileText }, { label: 'Data Quality', path: '/app/data-quality', icon: Filter }] }];
const roleLabels: Record<UserRole, string> = { faculty: 'Faculty', program_coordinator: 'Program Coordinator', department_head: 'Department Head', administrator: 'Administrator' };
export function Shell({ children }: { children: ReactNode }) { const location = useLocation(); const { role, sidebarOpen, setSidebarOpen, setRole } = useUiStore(); return <div className="app-shell"><aside className={`sidebar ${sidebarOpen ? 'open' : ''}`}><div className="brand"><span className="brand-mark">C</span><span>classpulse</span><button className="close-sidebar" onClick={() => setSidebarOpen(false)} aria-label="Close navigation"><X size={18} /></button></div><div className="workspace-switcher"><div className="school-mark">SV</div><div><strong>Saint Victoria College</strong><span>{roleLabels[role]} workspace</span></div><ChevronDown size={15} /></div><nav>{groups.map((group) => <div className="nav-group" key={group.label}><span className="nav-label">{group.label}</span>{group.items.map(({ label, path, icon: Icon }) => <Link className={`nav-item ${location.pathname.startsWith(path) ? 'active' : ''}`} key={path} to={path} onClick={() => setSidebarOpen(false)}><Icon size={17} /><span>{label}</span>{label === 'At-Risk Students' && <span className="nav-count">47</span>}</Link>)}</div>)}</nav><div className="sidebar-bottom"><button className="nav-item" onClick={() => setRole(role === 'administrator' ? 'faculty' : 'administrator')}><Settings size={17} /><span>Switch role</span></button><Link className="nav-item" to="/app/settings"><Settings size={17} /><span>Settings</span></Link><div className="user-card"><Avatar initials="CR" className="user-avatar" /><div><strong>Camille Reyes</strong><span>{roleLabels[role]}</span></div></div></div></aside><div className="main-area"><header className="topbar"><button className="mobile-menu" onClick={() => setSidebarOpen(true)} aria-label="Open navigation"><Menu size={20} /></button><div className="breadcrumbs"><span>Workspace</span><ChevronRight size={14} /><strong>{location.pathname.split('/').filter(Boolean).pop()}</strong></div><div className="topbar-actions"><div className="top-search"><Search size={16} /><span>Search anything</span><kbd>⌘ K</kbd></div><button className="top-icon" aria-label="Notifications"><Bell size={18} /><i /></button><button className="top-icon" aria-label="Help"><CircleHelp size={18} /></button><Avatar initials="CR" className="top-avatar" /></div></header>{children}</div></div>; }
