import { zodResolver } from '@hookform/resolvers/zod';
import { ChevronRight, Eye, EyeOff } from 'lucide-react';
import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { useNavigate } from 'react-router-dom';
import { z } from 'zod';
const schema = z.object({ email: z.string().min(1, 'Enter your email or username'), password: z.string().min(1, 'Enter your password') });
type FormValues = z.infer<typeof schema>;
export function LoginPage() { const navigate = useNavigate(); const [showPassword, setShowPassword] = useState(false); const { register, handleSubmit, formState: { errors, isSubmitting } } = useForm<FormValues>({ resolver: zodResolver(schema) }); const onSubmit = async () => { await new Promise((resolve) => setTimeout(resolve, 500)); navigate('/app/dashboard'); }; return <div className="login-screen"><div className="login-visual"><div className="login-brand"><span className="brand-mark">C</span><span>classpulse</span></div><div className="login-message"><p className="eyebrow">Attendance intelligence</p><h1>Make every attendance signal actionable.</h1><p>One clear view for the people helping students show up, stay on track, and succeed.</p><div className="login-stat"><strong>92.4%</strong><span>average attendance this term</span><i /></div></div><span className="login-footer">Saint Victoria College · 2024–2025</span></div><div className="login-panel"><div className="login-panel-inner"><div className="mobile-login-brand"><span className="brand-mark">C</span><span>classpulse</span></div><p className="eyebrow">Welcome back</p><h2>Sign in to your workspace</h2><p className="login-copy">Use your school account to continue.</p><form onSubmit={handleSubmit(onSubmit)}><label>Email or username<input type="text" placeholder="you@saintvictoria.edu" {...register('email')} />{errors.email && <small className="field-error">{errors.email.message}</small>}</label><label>Password<div className="password-field"><input type={showPassword ? 'text' : 'password'} placeholder="Enter your password" {...register('password')} /><button type="button" aria-label="Toggle password visibility" onClick={() => setShowPassword(!showPassword)}>{showPassword ? <EyeOff size={17} /> : <Eye size={17} />}</button></div>{errors.password && <small className="field-error">{errors.password.message}</small>}</label><div className="login-options"><label className="checkbox-label"><input type="checkbox" /> <span>Remember me</span></label><button type="button" className="link-button" onClick={() => navigate('/forgot-password')}>Forgot password?</button></div><button className="login-submit" type="submit">{isSubmitting ? 'Signing in…' : 'Sign in'} {!isSubmitting && <ChevronRight size={16} />}</button></form><p className="login-help">Having trouble signing in? <button className="link-button">Contact your administrator</button></p></div></div></div>; }
